spring:
  profiles:
    active: prod

server:
  servlet:
    context-path: /auth-service
  port: ${SERVER_PORT:9191}
  tomcat:
    threads:
      max: ${TOMCAT_MAX_THREADS:50}
      min-spare: ${TOMCAT_MIN_THREADS:20}
    accept-count: ${TOMCAT_ACCEPT_COUNT:300}
    basedir: /
    accesslog:
      enabled: true
      directory: "/logs/auth-service"
      prefix: access_log
      buffered: false
      suffix: .log
      file-date-format: .yyyy-MM-dd
      pattern: "%h %l %u %t %r %s %b %D"